### ISSUE TITLE
Main pages updates: Our mission section

### ISSUE THREAD

**Issue by Erioldoesdesign** [foss-responders/fossresponders.com#101]
So quite a few things have changed on the website designs that didn't get captured here. I'm breaking them into a few issues.

Most up to date page mock-up:
https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/screen/563447da-d7d4-4adc-9739-b8cf99a0687c/Version-4-23-04-2020?fullscreen

This issue is for this section 'Our mission':
<img width="670" alt="Screenshot 2020-05-19 at 19 30 42" src="https://user-images.githubusercontent.com/11681324/82364744-998fad00-9a07-11ea-97f9-7303badb8d7d.png">

- Change section title to 'Our Mission'
- Change the first copy section to read 'Our purpose is to provide a crowd-sourcing approach to help those in the open source community affected by corona virus, especially in the face of event cancellations.'
- Chnage button copy to 'Join the growing FOSS responders'
- Change button icon to: https://drive.google.com/open?id=1D_e-aVASkjgrO5olNiQ3OO447oy5XmvR
- The image's file name was previously 'who we are.svg' and is now 'our mission.svg' : https://drive.google.com/open?id=1msDboTTdz9uYnOFFCPvvHGeUW-YYuUBP

- Remove the text that reads 'This working group is made up of individuals and organizations including:
Duane O’Brien, Megan Byrd-Sanicki, Richard Littauer, Nuritzi Sanchez, Tony Urso, Alyssa Wright, Rachel Lawson, Allen Gunn, Eriol Fox , Devon Zuegel, Jacob Redding, Ruth Suehle, Michael Cheng, Damon Gregory, Scott Moore, Shirley Bailes, Jocelyn Matthews, Saptak Sengupta…and more!'
- Global Nav text becomes 'our mission'

Pending a final decision from team
- Remove the support logos so they can be located in the https://fossresponders.com/about/ page as per about page mock-up
https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/screen/62aa147d-d557-486e-8963-b22ed7883c57/About-page-version-1-29-04-2020?fullscreen

**Comment by SaptakS** [comment]
On it!

**Comment by Erioldoesdesign** [comment]
@SaptakS I'm just waiting on final confirmation that the supporter logos move to the about page. So until we hear a yes/no that part stays.
