### ISSUE TITLE
Main pages updates: Blog section

### ISSUE THREAD

**Issue by Erioldoesdesign** [foss-responders/fossresponders.com#105]
So quite a few things have changed on the website designs that didn't get captured here. I'm breaking them into a few issues.

Most up to date page mock-up:
https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/screen/563447da-d7d4-4adc-9739-b8cf99a0687c/Version-4-23-04-2020?fullscreen

This issue is for this section 'Blog':
<img width="610" alt="Screenshot 2020-05-19 at 19 55 32" src="https://user-images.githubusercontent.com/11681324/82366823-c2fe0800-9a0a-11ea-8138-c0948cdee4ad.png">

- Image for the section:https://drive.google.com/open?id=1A6SNVK1PKUvWgZw3z1Otheev6_moUPQG
- First copy section to read: 'Read articles from the Foss Responders team and other people who are working to help keep open source healthy during corona virus.'
- Second copy section pulls in the most recent article title and sample/preview text from the blog page: https://fossresponders.com/blog/
- First button (brand yellow #FFDD57) text 'Read the full article' with icon: https://drive.google.com/open?id=1oq3EAnMuJKgD7I5eG-3dYIHY78Dr1wnH should link to the most recent blog article that also appears the the preview title/text above the button
- Second button (brand green #7BC9AC) text 'View all articles' icon: https://drive.google.com/open?id=14OTNj8D-iVatsg_uHcApdxlpOpPXBvof should go to the main blog page: https://fossresponders.com/blog/

**Comment by RichardLitt** [comment]
Stale. Thank you, @Erioldoesdesign. Feel free to reopen if you feel it is necessary.
