### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by Erioldoesdesign** [foss-responders/fossresponders.com#106]
Looks like the links that are/will be missing are:

'our mission' (changed from older who we are section #101 )

'who we are' (added in #104 )

'events' (already existing)

**Comment by Erioldoesdesign** [comment]
Blocked by #101 and #104

**Comment by RichardLitt** [comment]
I added these in, but now it looks pretty cluttered. Ideas?

**Comment by Erioldoesdesign** [comment]
I got it all on one line by fiddling around with the font size (16 t0 15) renaming 'About our programs' to 'Our Programs' and changing the flex (?) in the spacing of the columns.

Ended up with this:

![Screenshot 2020-05-20 at 16 11 41](https://user-images.githubusercontent.com/11681324/82463335-9ef70100-9ab4-11ea-9780-1613e7298f44.png)

**Comment by RichardLitt** [comment]
Done.
