### ISSUE TITLE
Top nav improvements

### ISSUE THREAD

**Issue by Erioldoesdesign** [foss-responders/fossresponders.com#107]
So the current global nav is awesome, but we could make it even more awesome 😄 

<img width="687" alt="Screenshot 2020-05-19 at 20 19 55" src="https://user-images.githubusercontent.com/11681324/82368940-2178b580-9a0e-11ea-9cbd-361e0fe315c6.png">

When a user is at the top of the fossresponders page, the nav has an underline in brand blue #58B2E4 5px high.

As the user scrolls, the top nav is sticky.

As the user scrolls the foss responders logo (https://drive.google.com/open?id=1xPxmLTwacQ5BiSLecF2EI4I7jfijQMeL) aligns to the left side of the nav bar. 

As the user scrolls or clicks on a nav item, that current section gets an 'arrow' pointing up to that section in the navbar and the text becomes bold and changes to the brand darker blue #2292CE :
<img width="687" alt="Screenshot 2020-05-19 at 20 21 33" src="https://user-images.githubusercontent.com/11681324/82369360-cabfab80-9a0e-11ea-8a17-ca6b9ea2c9e6.png">

**Comment by RichardLitt** [comment]
Stale. Thank you, @Erioldoesdesign. Feel free to reopen if you feel it is necessary.
