### ISSUE TITLE
Blog images display squished

### ISSUE THREAD

**Issue by Erioldoesdesign** [foss-responders/fossresponders.com#119]
![Screenshot 2020-06-23 at 14 25 31](https://user-images.githubusercontent.com/11681324/85409970-6be5d880-b55e-11ea-9688-2e2afb56107f.png)

![Screenshot 2020-06-23 at 14 25 34](https://user-images.githubusercontent.com/11681324/85409971-6daf9c00-b55e-11ea-8447-1106694d9386.png)

https://fossresponders.com/blog/

It looks like the images that are used alongside the blog posts get squished in a strange way. There probably needs to be either a second, square ratio image uploaded as part of the blog post thumbnail or some way of doing image 'cropping' 

Thoughts tech folks?

**Comment by SaptakS** [comment]
Interesting. Seems it gets stretched in chrome while in firefox, the height is auto and is not stretched 

This is what I see in 800 px screen resolution in firefox:
![image](https://user-images.githubusercontent.com/9530293/85415781-5aff8c00-b58b-11ea-85fe-1657ead3cfed.png)


This is what I see in my 2k monitor resolutions in firefox:
![image](https://user-images.githubusercontent.com/9530293/85415866-6eaaf280-b58b-11ea-8a85-3144b9dda801.png)

I would prefer a second square ratio image as the best way to go about it. Still, I think one easy solution can be to replicate the same behaviour as seen in firefox. Need to investigate why two behave separately.
