### ISSUE TITLE
A 'orphaned' post at the bottom of the blog page

### ISSUE THREAD

**Issue by Erioldoesdesign** [foss-responders/fossresponders.com#120]
![Screenshot 2020-06-23 at 14 25 49](https://user-images.githubusercontent.com/11681324/85411921-e4e62f80-b560-11ea-8647-f188f76e00f0.png)

When you scroll to the bottom of the blog page you see the above. The text or logo/image isn't clickable and I'm not sure what it's in reference to or why its there :(

https://fossresponders.com/blog/events/join-us-at-uplift-by-foss-responders/

**Comment by SaptakS** [comment]
So any blog posts after the two latest post goes to that section. The link missing is probably a mistake on my part. I guess I missed adding a link. I will send a PR fixing that.

**Comment by RichardLitt** [comment]
Can't replicate. I think this is closed.
