### ISSUE TITLE
Global navigation on blog page

### ISSUE THREAD

**Issue by Erioldoesdesign** [foss-responders/fossresponders.com#122]
https://fossresponders.com/blog/

The blog page currently uses breadcrumbs instead of the global navigation. 

Can we add the global navigation to all blog pages but also, keep the breadcrumb.

So it'd look like this mockup:
![Blog with nav ticket #](https://user-images.githubusercontent.com/11681324/85523845-642a4080-b5ff-11ea-9d28-18f7f86df4c4.png)

**Comment by RichardLitt** [comment]
Stale. Thank you, @Erioldoesdesign. Feel free to reopen if you feel it is necessary.
