### ISSUE TITLE
Create a FOSS-Responders Discourse

### ISSUE THREAD

**Issue by nuritzi** [foss-responders/fossresponders.com#13]
As part of the FOSS-Responders initiative, it'd be great to set up a Discourse instance. 

We can then use this to post meeting notes for those interested in following our progress, and it can be a place where the community goes to support each other. 

It looks like Discourse offers [free hosting for Open Source projects](https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/). We should look into getting a free hosted instance set up. 

@nuritzi has experience setting up groups within Discourse once we set it up . We are seeking someone to help set up the instance.

**Comment by nuritzi** [comment]
Adding some notes from @eriolfox on the Open Collective #crisis-working-group Slack that we can post once we have the discourse set up. I wasn't sure where to jot them down, so adding them here for now. 

### Pro-bono design resources
 * [Open Source Design](https://discourse.opensourcedesign.net/) - For OSS design contributions you can ask for that here.
 * [Virtual Design Sprint](https://www.virtualdesignsprint.com/) Organises design sprints remotely
 * [Hague Hacks](https://thehaguepeace.org/haguehacks/) - Does in person design thinking for humanitarian crisis and links with OSS projects to make them 'exist'
 * [OpenIDEO](https://www.openideo.com/) - does funded challenges more to do with humanitarian stuff: 
 * [Open Design](https://opendesign.ushahidi.com/ ) - A project to create accessible processes for designers to collaborate and contribute to open source software:

**Comment by nuritzi** [comment]
Michael Downey offered to help with Discourse on the foundations@ list. I'm in contact with him and we'll update this issue if we're able to move things forward together.

**Comment by DuaneOBrien** [comment]
Recommend transferring this issue to https://github.com/foss-responders/about/ so that we can keep this repo focused on Website issues.

**Comment by nuritzi** [comment]
@DuaneOBrien sure, do you know how to do that? Can we just move it, or do we have to close and re-open? 

Thanks for the suggestion!

**Comment by nuritzi** [comment]
Per @downeymj: (https://github.com/foss-responders/about/issues/7#issuecomment-601903599)

> I am going to send off a couple referals to experts I know who have volunteered at the [Discourse community call for volunteers](https://meta.discourse.org/t/calling-out-for-volunteer-community-managers/144783) for pandemic related activities. Will be sending them emails and copying @nuritzi today.

>Once the website is set up through the Discourse.org hosting free trial, I'll then send an email intro to the Discourse team to ask them about their hosting offer. @nuritzi will send me an email once that's done with the chosen URL so I can point the team to the correct account/site.

**Comment by nuritzi** [comment]
Here are my notes from my meeting with @downeymj on Friday. Michael, please feel free to clarify if I missed anything!

## 2020-03-20 Notes | Michael <> Nuritzi 

### Timeframe
 * Plan for supporting the FOSS community through this initiative for 18 months (based on current WHO predictions)

There may be similar types of groups popping up, so we might want to keep in mind merging efforts with someone else eventually. Merging Discourse is pretty easy. It's a good investment. Pretty flexible, can keep it simple, and if you want different kinds of programs, then those can grow organically. 

### Structuring Discourse
Start conservatively. Have a free-for-all conversation area, and do specific outreach. Have a category called cancelled events. Have people start topics for each event. Have a template for people to fill out. People can follow up with specific questions or comments. 
 
Can turn a topic into a wiki post. The first post in the topic can become a wiki style page that people can edit. For example, it can hold a list of which events are cancelled. 

#### Things we want in our discourse instance / possible categories
 * **General** -  a free-for-all conversation area
 * **FOSS Matchmaking** - People can volunteer a specific skill or thing, each in a separate thread (e.g. designers can volunteer like how community managers did in the [discourse call for community managers thread](https://meta.discourse.org/t/calling-out-for-volunteer-community-managers/144783) thread)
 * **Resources** - a place where people can post resources they've found helpful (e.g. [see this list we've started to compile](https://github.com/foss-responders/about/issues/7))
 * **Cancellations** - a list of FOSS event cancellations
 * **Funding Q&A** - a space for people to ask about how to get resources. Provide an FAQ about how to access resources. 
* **Stories** -- we want to collect stories about how we are helping the community in order to fundraise 
* **International** -- this might be good to set up for some of the major languages, and add more subcategories if there's a critical mass of conversations in that language.

### Process Integration
Internal program management discussions could happen in Discourse. Operations on GitHub, general public on Discourse. All requests might start convo in Discourse, and track status in GitHub. 

### Language Support
 - OSS contributions are mostly happening in English, although there's an exception of that in China.
 - There's a great plugin for auto-translations. Can do real-time translations. Re-rendering of the page. 
 - If people are posting questions in other languages -- maybe have an international category. You can create an international top category and sub-categories for difference languages. Have a moderator for each of those. Make sure you write Francais, not French, for example. Make sure category description is in that native language. 

### What do we need to get started? 
 * URL for discourse set up. @RichardLitt can you help us set up community.fossresponders.com? 
 * Short list of volunteers that are content moderators. 
 * Logos -- can update that later if needed.
 * Content blurbs. Topic descriptions and all that. 

### Other Considerations
 * Make sure that folks' questions are answered in a timely way. 
 * Stoke conversation and ask questions of people. 
 * Update meeting notes. Have working groups post things there to engage the community.

**Comment by nuritzi** [comment]
@downeymj just an FYI that I'm going to wait until tomorrow to see if we can get the URL sorted before we start. Plus, tomorrow I'll be speaking with one of the people you connected me to, so can get his input too before I start creating things. 

Will send you the link to the discourse instance asap once it's set up!

**Comment by nuritzi** [comment]
@downeymj: Richard just helped us set up the URL (Thanks, @RichardLitt!), so we now have the instance running on: https://community.fossresponders.com/

I haven't done much customization yet, so it's not quite ready to "launch" aka be linked to from the website. Michael - are you able to ping the Discourse people about its free trial status now, or would you prefer to wait? 

I'll update this thread with any changes to the discourse instance and will make it clear when I think it's reached the MVP stage and is ready to launch.

**Comment by nuritzi** [comment]
Just an update: thanks to Tobias, the Discourse instance is in much better shape and pretty close to being ready to launch more publicly. We've started to [request feedback on the current categories](https://community.fossresponders.com/t/what-categories-and-subcategories-should-we-add/35). 

Next, I want to talk to some of the people from the working group about processes/workflow/tools, as Yaw suggested.

We're moving along quickly -- thanks again to everyone involved so far!

**Comment by RichardLitt** [comment]
I believe that this can be closed. Thank you, @nuritzi for driving this!
