### ISSUE TITLE
Set up a Matrix bridge for Slack

### ISSUE THREAD

**Issue by nuritzi** [foss-responders/fossresponders.com#15]
One of the pieces of feedback we've heard consistently from the FOSS community is that we should try to use more FOSS tools as we continue to respond to the COVID-19 crisis. In an effort to do this, and to allow people to have the option of using open source tools, we should set up a Matrix bridge to Slack. 

### To-Dos
 * [ ] Create Matrix bridge to Slack
 * [ ] Post about the bridge on the website

**Comment by nuritzi** [comment]
Michael Downey and Matthew Hodgson responded to my request for help on Twitter and helped us set up a Matrix bridge. Michael tested it out and it seems to be working well. 

## Matrix Bridge Info
 #fossresponders:matrix.org on the Matrix network


@RichardLitt can you please add this info to the website? If there's a way to get a one-click link so that people can join that Matrix room directly, that would be ideal. I'm seeing if Michael knows about that since I'm not super familiar with Matrix bridges.

**Comment by RichardLitt** [comment]
Done! Thank you.
