### ISSUE TITLE
Clarify who we serve on fossresponders.com

### ISSUE THREAD

**Issue by tmurso** [foss-responders/fossresponders.com#20]
Let's make it exceptionally clear who this initiative is meant to support so people who come to the site understand if this is for them and what to do if it's not.

**Comment by Erioldoesdesign** [comment]
Pretty sure this will be linked to the 'Personas' issue #17

**Comment by Erioldoesdesign** [comment]
Also pretty sure this is served by the website layout design in issue #8 

Prototype links here: https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/

**Comment by RichardLitt** [comment]
I think we got this.
