### ISSUE TITLE
Create design assets for Discourse

### ISSUE THREAD

**Issue by nuritzi** [foss-responders/fossresponders.com#23]
@Erioldoesdesign -- as per your request on issue #10, I'm opening an issue for assets now that we've decided on branding. Can you please help create some assets for Discourse? 

I've copy and pasted all of the options they give. I think it's fine to just update the ones you think will make the most impact, especially if you're short on time. 

Also, do you have a list of colors we'll use for branding? If so, I'll update the categories in Discourse with them!

## List of assets to personalize Discourse
 Link to where they need to go once assets are ready: https://community.fossresponders.com/admin/site_settings/category/branding

### Favicon
A favicon for your site, see https://en.wikipedia.org/wiki/Favicon. To work correctly over a CDN it must be a png. Will be resized to 32x32. If left blank, large_icon will be used.

### Logo big
The logo image at the top left of your site. Use a wide rectangular image with a height of 120 and an aspect ratio greater than 3:1. If left blank, the site title text will be shown.

### Logo small
The small logo image at the top left of your site, seen when scrolling down. Use a square 120 × 120 image. If left blank, a home glyph will be shown.

### Mobile logo
The logo used on mobile version of your site. Use a wide rectangular image with a height of 120 and an aspect ratio greater than 3:1. If left blank, the image from the `logo` setting will be used.

### Large icon
Image used as the base for other metadata icons. Should ideally be larger than 512 x 512. If left blank, logo_small will be used.

### Digest logo
The alternate logo image used at the top of your site's email summary. Use a wide rectangle image. Don't use an SVG image. If left blank, the image from the `logo` setting will be used.

### Maniphest icon
Image used as logo/splash image on Android. Will be automatically resized to 512 × 512. If left blank, large_icon will be used.

### Twitter summary large image
Twitter card 'summary large image' (should be at least 280 in width, and at least 150 in height). If left blank, regular card metadata is generated using the opengraph_image.

### Opengraph icon
Default opengraph image, used when the page has no other suitable image. If left blank, large_icon will be used

### Apple touch icon 
Icon used for Apple touch devices. Will be automatically resized to 180x180. If left blank, large_icon will be used.

---- 
Thanks in advance for your help with this!

**Comment by Erioldoesdesign** [comment]
Okay just finished making these sizes on the XD link and just exporting now!
https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/

Generally I'm going to export with white backgrounds so please let me know if we need transparent .png 's

Will put in this folder: https://drive.google.com/drive/folders/1lYBWCiidYTf_CIavqKe4l05HC5llmys7?usp=sharing

**Comment by Erioldoesdesign** [comment]
Can this issue be closed? @nuritzi

**Comment by RichardLitt** [comment]
Thanks, @Erioldoesdesign :)
