### ISSUE TITLE
Integrate link checking

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#29]
Right now, there's no validators. 

Same goes for Markdown validators.

**Comment by justwheel** [comment]
Maybe you already know about this, but [html-proofer](https://github.com/gjtorikian/html-proofer) is reaaaally nice for this. I integrated it into a Jekyll Travis CI pipeline over here:

https://github.com/FOSSRIT/fossrit.github.io/blob/81228b4276588b336af332943bdc9951cc4a4b68/Rakefile

**Comment by RichardLitt** [comment]
Yep! Would be sweet to integrate that, here. This issue was opened for me to look into it.
