### ISSUE TITLE
Create the blog page design for fossresponders.com

### ISSUE THREAD

**Issue by Erioldoesdesign** [foss-responders/fossresponders.com#36]
Fossresponders are looking to cross-post blog content to their site and require a new page design/layout for articles/blog pieces.

Developers will implement the blog in Jekyll.

This is the first article that will be cross-posted:
https://engineering.indeedblog.com/blog/2020/03/support-the-oss-community/

The blog pages should layout text well, readable with appropriate headings and ability to share the blog post on social media.
The brand styling should be used in the design but the brand styles can be extended and developed to support this new kind of page content/context.

Ability to sort by and add categories for articles.

Fossresponders website team - please add other requirements/considerations for design in this issue or in comments on this issue :)

**Comment by RichardLitt** [comment]
First PR open in #42. Needs design.

Requirements: show blog author(s) with links out to their pages. Otherwise, use your discretion, I think.

**Comment by RichardLitt** [comment]
Part of #32.

**Comment by alisonjudy** [comment]
Hi Eriol, can we add a section that allows for us to create categories? Thanks!

**Comment by RichardLitt** [comment]
Categories can be made easily on the back end in the draft. However, a section for displaying these and sorting by them would be great!

**Comment by Erioldoesdesign** [comment]
Progress links:
https://www.figma.com/file/eqiXamWjAerrBr4ajtLf5Z/foss-responders?node-id=26%3A132
https://www.figma.com/proto/eqiXamWjAerrBr4ajtLf5Z/foss-responders?node-id=23%3A919&viewport=-963%2C54%2C0.13521051406860352&scaling=min-zoom

Feeding back on these by 12/04/20

**Comment by awright** [comment]
i really like them! are there differences we should be responding to? they
all look great to me ;)

**Comment by alisonjudy** [comment]
LGTM. The only thing I would add is a twitter logo at the bottom of the page in the footer so we could link there.

**Comment by RichardLitt** [comment]
@ognarb Want to help with this?

**Comment by CarlSchwan** [comment]
yes :) what design should I implement and how should it look on mobile?

**Comment by CarlSchwan** [comment]
I started working on it in https://github.com/foss-responders/fossresponders.com/pull/49

Note that a search bar won't be possible, at least not without an external service.

**Comment by RichardLitt** [comment]
Awesome! Thank you. See the design, above. Also, make sure to work off of my branch in #46 - I added Bootstrap. :)

**Comment by Erioldoesdesign** [comment]
@jaysethi can you please support @ognarb as this build develops?

**Comment by jaysethi** [comment]
Hi yes of course, I'm on it

**Comment by jaysethi** [comment]
Just finished the Blog post reader interface, would appreciate feedback: https://www.figma.com/file/eqiXamWjAerrBr4ajtLf5Z/foss-responders?node-id=26%3A132

**Comment by RichardLitt** [comment]
Looks good to me, @jaysethi!

What happens if a blog post doesn't have a photo? 

@ognarb Look alrigt to you to implement?

**Comment by SaptakS** [comment]
@jaysethi @RichardLitt @Erioldoesdesign I have some questions in the implementations. It might be repetitive but I couldn't find any mentions, so apologies if I am repeating something.

- So in the design, after the 2 latest posts, there is a section with 3 horizontally placed posts. Are these the next 3 posts chronologically after the latest posts?
- There is a section below the 3 horizontally stacked posts, with a post spanning the entire width, is that some kind of featured post? If yes, then I think that section stays empty if no featured posts.
- I am guessing the rest of the posts in the 3 column grid are the remaining blog posts.
- In case, when there is only one post, we show only the latest section with categories and authors in the right?
- what happens to categories and authors part in a mobile screen?

**Comment by Erioldoesdesign** [comment]
HI FRIEND :) @SaptakS these are definitly questions for @jaysethi as he created these designs but I just wanted to say hello.

**Comment by SaptakS** [comment]
@jaysethi Also another point. The blog post images in the latest blog section are considered to be in a portrait format, whereas I am assuming mostly a blog image will be landscape or square given the rest of the sections are assuming that?  I am guessing, in that case, the width and layout will change a bit?

**Comment by jaysethi** [comment]
hi, these are some valid points and considerations that I will try to implement - I have answers to a couple of the questions/comments you've written, but figma is refusing to cooperate and isn't letting me open the designs - i will get back to you tomorrow morning when figma is hopefully being more helpful.

**Comment by SaptakS** [comment]
@jaysethi great! No issues!

**Comment by RichardLitt** [comment]
@jaysethi Just checking in. Any word on this? :)

**Comment by jaysethi** [comment]
Hello, yes:
1. I have changed the arrangement - now the top 2 posts (can be up to 4) are featured, then horizontal posts are latest (chronologically)
2. The big post is a featured post too yes.
3. yes
4. When there is only one post (up to 4) it then appears where featured posts are right now.
5. the categories and authors become a drop-down menu (like the one shown in the Canceled Conferences screen ("Macbook - 12"))
6. If the image is landscape instead of portrait you can reduce the height of the image frame (and maintain the relative position of the title and the preview text) while maintaining the width.

**Comment by SaptakS** [comment]
> I have changed the arrangement - now the top 2 posts (can be up to 4) are featured, then horizontal posts are latest (chronologically)

What if there is no featured? Does the page start from the horizonatal posts? What I have right now is this: https://deploy-preview-79--fossresponders.netlify.app/blog/ where the latest 2 are shown like that, and then the remaining blogs are shown in a 3 column grid. And this is the category page: https://deploy-preview-79--fossresponders.netlify.app/category/cancelled_conference/

> the categories and authors become a drop-down menu

In all pages?

cc: @jaysethi @RichardLitt

**Comment by jaysethi** [comment]
I figured there always would be featured, no? Use the vertical stack for latest posts (along with horizontal stack) when there are no featured posts.
yes, in all pages.
also, please implement the breadcrumbs nav on the blog pages, and please make the top left icon clickable to go to the home page.

**Comment by SaptakS** [comment]
@jaysethi One last thing. Can you give me a design for the dropdown expanded?
