### ISSUE TITLE
Create the FAQ page design for fossresponders.com

### ISSUE THREAD

**Issue by Erioldoesdesign** [foss-responders/fossresponders.com#37]
fossresponders.com will have a separate page with the frequently asked questions.

This page requires a new/different layout style than the main page and blog/article page. It should be focussed on the question/answers and a process in which to submit a question that hasn't already been asked/answered.

For the FAQS the layout text well, readable with appropriate headings and question to answer connection.
The brand styling should be used in the design but the brand styles can be extended and developed to support this new kind of page content/context.

**Comment by nuritzi** [comment]
I thought that during the [website subgroup meeting we decided on discourse for the FAQ](https://docs.google.com/document/d/1KRqxX_vRZnnc_vuE5qMcvpcbl_DOPgEaiKNKznpvuA8/edit). If not, that's fine! I created a "[Funding QA](https://fossresponders.discourse.group/c/resources/funding/10)" subcategory but am holding off from adding anything to it in case we decide not to use discourse. Just let me know!

**Comment by awright** [comment]
Is the FAQ for funding or about the FOSS Responders group? Either way, it
makes sense to put Funding question it in Discourse. That way others can
add funding resources as they see fit.

And we keep the website FAQ specific to the overarching mechanism of the
foss responders working group.

**Comment by Erioldoesdesign** [comment]
The decision from Nuritzi and Richards meeting on Thursday 9th after the regular meeting was to still have  static FAQ page on the website because this reiterates the 'authority' of that FAQs and limits community members from answering questions via discourse 'unofficially' however, we will also have a FAQs section on discourse to capture community questions and any questions that crop up via any channel (discourse, email, twitter etc.) will be picked up by the FAQ's sub-group and added by a web dev on the website.

**Comment by RichardLitt** [comment]
Sounds about right to me. I can re-enable as soon as I have a design, @Erioldoesdesign :)

**Comment by Erioldoesdesign** [comment]
Looks like this one has fallen through the net. @jaysethi were you working on this design? if not I can work on it :)

**Comment by jaysethi** [comment]
Hi yes please go ahead, I'm sorry things have been really crazy lately.

**Comment by RichardLitt** [comment]
> I'm sorry things have been really crazy lately.

No need to apologize. A lot of us are in that boat. :) Stay well.

**Comment by RichardLitt** [comment]
Stale. Thanks, all.
