### ISSUE TITLE
Redirect old URL to new URL for Discourse

### ISSUE THREAD

**Issue by nuritzi** [foss-responders/fossresponders.com#40]
We applied for a free discourse instance since our trial was running out and they granted it to us because we qualified for their Discourse for Open Source program + Michael Downey helped introduce us to the team. 

The transition went smoothly but since it's a free instance that's hosted on Discourse, they require us to use a subdomain: fossresponders.discourse.group

Can someone please help to redirect community.fossresponders.com to fossresponders.discourse.group asap? 

Thank you!

**Comment by RichardLitt** [comment]
This should be done. Let me know if this can be closed and it works!

**Comment by nuritzi** [comment]
@RichardLitt that seems to have worked. Thank you! 

Closing this issue as complete.

**Comment by RichardLitt** [comment]
I'm getting weird redirect errors at the moment. Hmm. Will have to look into it! Are you not, for https://community.fossresponders.com/?

**Comment by nuritzi** [comment]
Strange! I was getting weird errors yesterday, but today it seems to be working fine. I'm using Chrome as my browser. 

Maybe someone else can test too? @ognarb do you mind testing it out -- see any errors when you try to go to https://community.fossresponders.com/ ?

**Comment by RichardLitt** [comment]
Emailed Hover about it. Let's see!

**Comment by RichardLitt** [comment]
Update: Hover and Netlify are arguing about who is at fault. Still not sure how to resolve this. Working on it.

**Comment by RichardLitt** [comment]
Finally closed.
