### ISSUE TITLE
Set up authentication on Discourse

### ISSUE THREAD

**Issue by nuritzi** [foss-responders/fossresponders.com#41]
Whoever sets up the ‘official’ twitter, google and github accounts for fossresponders should be able to set up the logins, or else Tobias can help if we give him the logins. 

@RichardLitt let me know what you prefer. I think that you're the only one with the login info for official accounts as of now, right? Tobias has offered to either walk you through it on a video call, or else do it himself if you give him access to the logins.

**Comment by RichardLitt** [comment]
Done!
