### ISSUE TITLE
Create graphics for social media

### ISSUE THREAD

**Issue by alisonjudy** [foss-responders/fossresponders.com#44]
Twitter graphics:

Static images:
- [x] profile photo: 200x200
- [x] cover image: 1500x500

Photo templates all 1024x512:
- [x] blogs
- [x] press releases
- [x] events
- [x] apply for help
- [x] donate

**Comment by Erioldoesdesign** [comment]
@alisonjudy for the photo templates, do the graphics need to have those titles in text? I'm a bit confused what the photo templates are for/ in reference to?

Here's the twitter graphics though!
![Twitter Profile 200 x 200](https://user-images.githubusercontent.com/11681324/79155683-697e3a00-7dc9-11ea-88af-0d58838439c1.png)
![Twitter rectangle 1500x500 px](https://user-images.githubusercontent.com/11681324/79155687-6aaf6700-7dc9-11ea-88d7-68830fd50792.png)

**Comment by alisonjudy** [comment]
Thanks @Erioldoesdesign! It might be easier to do a quick zoom to discuss the other graphics (those can be backburner for now.) 

For the profile picture can we get one that will fit a little more nicely in a circle? Here's a screenshot of the twitter profile:

<img width="547" alt="Screen Shot 2020-04-13 at 3 09 37 PM" src="https://user-images.githubusercontent.com/22965526/79165954-0aa0cc80-7d99-11ea-8b14-707887c0c079.png">

From a style perspective, should we also move the FOSS Responders on the cover down a bit? Up to you. Thanks!

**Comment by Erioldoesdesign** [comment]
![Twitter Profile 200 x 200](https://user-images.githubusercontent.com/11681324/79566570-b05e7f00-80aa-11ea-9476-88284421002a.png)
Updated! :) @alisonjudy sorry for the delay!

**Comment by alisonjudy** [comment]
Thanks @Erioldoesdesign this looks great!!

**Comment by Erioldoesdesign** [comment]
Progress for the 1024x512 templates for the team are located here: https://docs.google.com/presentation/d/1Tx6_4f36vRmwn0mD_RJoYMRt7swv9yzuM7XUH_wEXNM/edit?usp=sharing

Ready for feedback, amends and suggestions!

**Comment by alisonjudy** [comment]
This looks great! Thank you so much @Erioldoesdesign! Can we add a slide with the color palette?

**Comment by Erioldoesdesign** [comment]
Cool! Gonna finish up some alt designs for: press releases, apply for help, donate next!

**Comment by Erioldoesdesign** [comment]
These are now Donezo! huzzah! https://docs.google.com/presentation/d/1Tx6_4f36vRmwn0mD_RJoYMRt7swv9yzuM7XUH_wEXNM/edit#slide=id.g74de7c61f7_4_89

**Comment by alisonjudy** [comment]
Hi @Erioldoesdesign can we lock that google slide deck so people know to make changes in a copy of the deck and not directly in your deck? Want to make sure we preserve your work!

**Comment by Erioldoesdesign** [comment]
@alisonjudy  Done! locked it down 🔒
