### ISSUE TITLE
Add a newsletter to keep updated about FOSS and COVID-19

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#5]

**Comment by Erioldoesdesign** [comment]
I could put together a coded newsletter template or happy to construct one if we're using Mailchimp or something similar.

**Comment by RichardLitt** [comment]
At the moment, we don't have the newsletter set up. I can sign us up for a Mailchimp, but I want to ensure that it'll be used before going through that effort. I'll bring this up with the communications team today.

**Comment by RichardLitt** [comment]
Stale.
