### ISSUE TITLE
Add in hr designs

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#53]
Right now, the horizontal rules lack the little icons on the end. I need the assets for these. These should also be added more proficiently to the list items.

**Comment by Erioldoesdesign** [comment]
Soooo I made them as .svg assets: https://drive.google.com/drive/folders/1rakP56NR9x90VVZo0cxufNy90bXHM-Nh?usp=sharing

but also idk I did some css and you could probs make the circles in css: https://codepen.io/Erioldoescode/pen/RwWorPO

I think I'm just trying to convince myself I could write css if I try hard enough. But positioning the hr  made me want to curl into a ball in the corner so I gave up.

**Comment by Erioldoesdesign** [comment]
Another web developer in my codebar session helped me fix this and clean it up https://codepen.io/stuartjnelson/pen/OJybOyw

**Comment by RichardLitt** [comment]
Oh, wow! That's so cool that you could make it work in CSS! Awesome!

**Comment by RichardLitt** [comment]
I think this is done?
