### ISSUE TITLE
Add dashed designs behind OC button

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#55]
I need the assets for these from @erioldoesdesign.

**Comment by Erioldoesdesign** [comment]
![need-help-title-underline](https://user-images.githubusercontent.com/11681324/79662369-78d7fb80-81ac-11ea-8315-0c5ef9a717ee.png)
![offer-help-title-underline](https://user-images.githubusercontent.com/11681324/79662383-79709200-81ac-11ea-9552-3a9b1fe99454.png)

Also here:https://drive.google.com/drive/folders/1rakP56NR9x90VVZo0cxufNy90bXHM-Nh?usp=sharing

**Comment by RichardLitt** [comment]
Thanks, @Erioldoesdesign. Stale, though, closing this now.
