### ISSUE TITLE
Link logos to sites

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#56]
The logos could easily be linked to the sites they represent.

**Comment by awelllle** [comment]
The logos of the organisations under 'who we are' right? I should be able to fix it up.
A link to their respective homepages should do, right?

**Comment by RichardLitt** [comment]
Yep! Just linking them to their own sites would be great. Wasn't a priority when I was making this, but would be nice to do. :) No styles should change.
