### ISSUE TITLE
Add a Privacy page

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#58]
We need better terms. I removed it, for now.

**Comment by rachellawson** [comment]
Added to today's agenda for Shirley Bailes, anyway - she is looking into content

**Comment by RichardLitt** [comment]
Thanks!

**Comment by Erioldoesdesign** [comment]
I'm guessing this will be pure text content with text hyperlinks. I can make a design mockup with that in mind but would be good to talk to Shirley Bailes if there's anything else that might be needed.

**Comment by Erioldoesdesign** [comment]
I got access to the Privacy document and I'll make a mockup. I can't think of any styles that would already exists though but I'll do it anyways 🤷‍♀️

**Comment by RichardLitt** [comment]
I don't think this needs extensive design. :) I can probably just hack it together with the basic text.

**Comment by Erioldoesdesign** [comment]
Nice nice nice I can relax 💆‍♀️

**Comment by RichardLitt** [comment]
Done!
