### ISSUE TITLE
Add a Twitter button in footer

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#59]
@erioldoesdesigns where did these icons come from? Can I get a Twitter one?

**Comment by Erioldoesdesign** [comment]
Font awesome! here ya go:
https://fontawesome.com/icons/twitter-square?style=brands

However, not all of the font awesome icons are in these neat little squares, like discourse: https://fontawesome.com/icons/discourse?style=brands

So I had to make that one and why I uploaded those to the design assets folder in my drive:
https://drive.google.com/drive/folders/1ziiGUYj4SCfaGQ-duvQycK4oluGnZJEg?usp=sharing

**Comment by RichardLitt** [comment]
Thanks! Got it.
