### ISSUE TITLE
Add hover and click states

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#61]
Right now, all of the buttons are static. I couldn't figure out how to get these colors from the design doc. @erioldoesdesign any ideas?

**Comment by Erioldoesdesign** [comment]
Hover states should be outlines like this kind of like the original:

<img width="632" alt="Screenshot 2020-04-18 at 19 45 27" src="https://user-images.githubusercontent.com/11681324/79665280-4da1dc00-81ad-11ea-9b5e-6f099c5f7419.png">

The border thickness is 2px

The hex colour codes you need are:

Blue = #2292CE
Pink = #ED4789
Green = #7BC9AC
Yellow = #FFDD57

Blue and Pink buttons have #FFF white text and arrow 
Yellow and Green buttons have #000 black text and arrow

Click states, I'm less concerned about as all the links travel/exit the page.

I'm thinking about making a .md file with the 'brand' in it if that'd be helpful?

**Comment by awelllle** [comment]
Let me take this up

**Comment by RichardLitt** [comment]
@awelllle Sure thing! Thank you!

**Comment by RichardLitt** [comment]
I think this is done.
