### ISSUE TITLE
Debate adding in world and heart images on mobile



### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#62]
I removed them as they were adding clutter to the mobile view. I think I can figure out where to put them back in, now, but advice would be good.

**Comment by Erioldoesdesign** [comment]
Agreed re. clutter but perhaps:

<img width="391" alt="Screenshot 2020-04-21 at 11 50 12" src="https://user-images.githubusercontent.com/11681324/79858001-95e81680-83c6-11ea-9ec7-0c6e88944fe0.png">

For the mobile view (eventually even we're prioritising our dev workload) we could do this orientation for all titles to save on vertical space in general.

**Comment by RichardLitt** [comment]
Stale. Feel free to reopen if you feel it is necessary. Thanks, @Erioldoesdesign.
