### ISSUE TITLE
Validate links

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#63]

**Comment by suehle** [comment]
The link on the main page to the May event is broken because it was copied from Slack and came along with the Slack redirect info.

**Comment by RichardLitt** [comment]
Thanks for the manual validation! Fixed. 

This issue should be closed when we have an automatic link validator set up.

**Comment by suehle** [comment]
I certainly have no aspirations to take the place of a validator. :) I just ran into that one when I tried to refer someone to it. Thanks!

**Comment by RichardLitt** [comment]
Duplicate of #29.
