### ISSUE TITLE
Add jekyll-assets plugin

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#66]
Right now, the Privacy page was removed partially because the asset path changes for images on secondary pages. We need an asset manager. Jekyll-asset should work. This will be important for the blog, too.

**Comment by SaptakS** [comment]
@RichardLitt I will probably add this along with the blog PR #79

**Comment by RichardLitt** [comment]
Stale. Feel free to reopen if you feel it is necessary.
