### ISSUE TITLE
Check on other browsers

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#67]
Browserstack, anyone?

**Comment by Erioldoesdesign** [comment]
In your QA of http://fossresponders.com/

Please include the following details:

**Desktop Hardware Details:**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone Hardware Details (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

Bugs in other browsers should then be raised as a new issue :)

**Comment by RichardLitt** [comment]
Hmm. Fair! I was thinking more using automated testing.

**Comment by SaptakS** [comment]
> In your QA of http://fossresponders.com/
> 
> Please include the following details:
> 
> **Desktop Hardware Details:**
> 
>     * OS: [e.g. iOS]
> 
>     * Browser [e.g. chrome, safari]
> 
>     * Version [e.g. 22]
> 
> 
> **Smartphone Hardware Details (please complete the following information):**
> 
>     * Device: [e.g. iPhone6]
> 
>     * OS: [e.g. iOS8.1]
> 
>     * Browser [e.g. stock browser, safari]
> 
>     * Version [e.g. 22]
> 
> 
> Bugs in other browsers should then be raised as a new issue :)

We can add this to the Github issue templates.

> I was thinking more using automated testing.

Maybe we can add some CI and integrate browserstack with it?

**Comment by RichardLitt** [comment]
> Maybe we can add some CI and integrate browserstack with it?

That was my goal. I don't think issue templates make sense for our amount of traffic at the moment.
