### ISSUE TITLE
Change wording around cancelled events

### ISSUE THREAD

**Issue by alisonjudy** [foss-responders/fossresponders.com#72]
Change from, "We are aggregating all of the cancelled, postponed, or virtual-only conferences affected by coronavirus. Take a look at the events here."

to: "We’re contributing to a database of all of the cancelled, postponed, or virtual-only conferences affected by COVID-19. Take a look at the events here."

Since we're contributing, not curating, it would be great to call out that we're also contributing to the community effort, and that we're not behind the actual airtable. 

From a comms standpoint, we should make sure that we are using COVID-19 vs "coronavirus."

**Comment by awelllle** [comment]
Can I go ahead and make those changes?

**Comment by alisonjudy** [comment]
Hi @awelllle, please do. Thanks!

**Comment by awelllle** [comment]
This has been fixed. I think this issue can be closed now. Changes are live.

**Comment by alisonjudy** [comment]
Thanks @awelllle! Can we change "coronavirus" to "COVID-19" in that text box for continuity? Thank you :)

**Comment by awelllle** [comment]
Done!

**Comment by RichardLitt** [comment]
Thanks, @awelllle and @alisonjudy!
