### ISSUE TITLE
Add About Us Page

### ISSUE THREAD

**Issue by alisonjudy** [foss-responders/fossresponders.com#73]
Add an 'About Us' or 'About The Team' page to the website. Would like to have:

- (Co)Leads at the top with their photo, org affiliation, links to profiles, and a short bio
- Volunteers below with their photo, org affiliation and links to profiles; listed in alphabetical order based on first or last name 

I've created a google form asking for the following information:
- Name
- Org Affiliation 
- Photo
- Twitter handle
- Linkedin profile link
- Github profile link
- Permission to post online from individuals and orgs
For (Co)Leads Only:
- Short bio

**Comment by Erioldoesdesign** [comment]
Did a design of this page here: https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/screen/62aa147d-d557-486e-8963-b22ed7883c57/About-page-version-1-25-04-2020

**Comment by alisonjudy** [comment]
Thanks @Erioldoesdesign! Can we add github link to the main section?

Can we also add a section where it's just the headshots and then name, where they work, then the Linkedin, github, twitter links?

**Comment by Erioldoesdesign** [comment]
@alisonjudy Will put on my to-do list for this week!

**Comment by alisonjudy** [comment]
Thanks @Erioldoesdesign!

**Comment by Erioldoesdesign** [comment]
I tried out a layout where the no-bio people were full width but it looked lonely and weird. So I went two-column: https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/screen/62aa147d-d557-486e-8963-b22ed7883c57/About-page-version-1-29-04-2020?fullscreen

For mobile though, they should all be full width stacked on top of each other :)

**Comment by alisonjudy** [comment]
@Erioldoesdesign this looks amazing! Is there a way we can add another line so we can say what committees people are on? Or is that going to be too cluttered? (Feel free to push back :))

**Comment by Erioldoesdesign** [comment]
@alisonjudy makes perfect sense to include so I've added here: https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/screen/62aa147d-d557-486e-8963-b22ed7883c57/About-page-version-1-29-04-2020?fullscreen

:D

**Comment by alisonjudy** [comment]
Looks amazing!!! Thank you!!

**Comment by RichardLitt** [comment]
This should be an entirely new page, right? I'm confused about the header and where it is supposed to fit, there.

**Comment by RichardLitt** [comment]
Also, could you give me the assets? :)

**Comment by alisonjudy** [comment]
Hi @RichardLitt, yes, should be a new page. I also just gave you access to the about me form responses to both the email addresses that I have. Apologies for the late reply!

**Comment by Erioldoesdesign** [comment]
@alisonjudy It's probably best that I create the profile images once we've had all our submissions from the team via the form.

**Comment by alisonjudy** [comment]
@Erioldoesdesign sounds good! I'll give you access to the file with all the form responses/images.

**Comment by Erioldoesdesign** [comment]
bg lines image and profile pics here: https://drive.google.com/drive/folders/1NAH1TqsFodkTFjuU-g03mdfXlz1Hc3rS?usp=sharing

**Comment by alisonjudy** [comment]
Thanks @Erioldoesdesign! They look fab!

**Comment by RichardLitt** [comment]
This is live.
