### ISSUE TITLE
Update Photo for hello@fossresponders.com 

### ISSUE THREAD

**Issue by awright** [foss-responders/fossresponders.com#74]
i cannot update the photo for the hello@ gmail account. @RichardLitt can you do it? i am thinking this "photo"

![79566570-b05e7f00-80aa-11ea-9476-88284421002a](https://user-images.githubusercontent.com/78410/80040140-4aa93300-84ae-11ea-83a0-23f9b73f50ac.png)

**Comment by RichardLitt** [comment]
Done! Thanks, Alyssa.
