### ISSUE TITLE
Add Top Navigation Links to Website

### ISSUE THREAD

**Issue by alisonjudy** [foss-responders/fossresponders.com#75]
Please add top navigation links/jump links to the website for each section. 

Nav links to include:

- Need Help
- Offer Help
- Events
- About Us [Can we do an arrow down or a list so people can go to: who we are (section already built out), new about the team page]
- About our program
- Contact

Thanks!

**Comment by awelllle** [comment]
hey @alisonjudy! I think I can fix this up. So 6 jump links on top, right? 

Then, for 'About Us', a dropdown, that has 2 links? 'who we are' and 'about the team'?

**Comment by alisonjudy** [comment]
Yes, that would be great @awelllle! The 'About the Team' page still needs to be built out, issue can be found [here](https://github.com/foss-responders/fossresponders.com/issues/73). Thank you!!

**Comment by Erioldoesdesign** [comment]
@awelllle I hadn't quite finished designs on this...Can you add a screenshot of what you worked up in code?

**Comment by awelllle** [comment]
oh, I had no idea. I have a screenshot and a link for you to see the changes

![Screenshot 2020-04-25 at 12 12 20 PM](https://user-images.githubusercontent.com/25726727/80278444-276cc680-86ee-11ea-8bd5-a34b8329e3dd.png)


Here's a link for you to see how it is
https://deploy-preview-76--fossresponders.netlify.app/



If this isn't what you had in mind, I can follow your lead.

**Comment by Erioldoesdesign** [comment]
Oh this looks great! :) definitely works as a 1st version nav

When we get more dev time I was thinking of adding things like Sticky nav, highlights on current section and adding the brand colours in:
https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/screen/563447da-d7d4-4adc-9739-b8cf99a0687c/Version-4-23-04-2020

https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/screen/96649c61-ee7a-4b42-bf89-5ea12f15ce0f/Nav-scroll

**Comment by awelllle** [comment]
Thanks.

Oh, yeah, those are actually cool! We could definitely do all of that. That nav scroll looks good.

**Comment by RichardLitt** [comment]
Done! Thanks, @awelllle.
