### ISSUE TITLE
Use .jpg instead of .png

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#78]
<img width="737" alt="Screen Shot 2020-04-27 at 21 29 33" src="https://user-images.githubusercontent.com/910753/80436902-38742e00-88ce-11ea-99ee-1453c58b2cff.png">

From [Page Speed Insights](https://developers.google.com/speed/pagespeed/insights/?url=fossresponders.com&tab=mobile).

**Comment by Erioldoesdesign** [comment]
Whoever helps with this can find the original files here: https://drive.google.com/drive/folders/185aEK0vOxGMB_773kGdQvPa0CU6dmPIj?usp=sharing

If that helps?

**Comment by RichardLitt** [comment]
It does! Thank you.

**Comment by Ruth-ikegah** [comment]
I will love to work on this issue but please I need a little explanation. Is this issue relating converting the images on the drive from .png to .jpg, then replacing it with the pictures on the images folder on the repository @RichardLitt

**Comment by RichardLitt** [comment]
Thanks, @Ruth-ikegah. Due to the project wind-down, I don't think that this needs to be done, at this time.

**Comment by Ruth-ikegah** [comment]
okay thanks @RichardLitt , if there is any other way I could help, please kindly point it my way, beginner open-source contributor here!

**Comment by RichardLitt** [comment]
Thanks, @Ruth-ikegah! https://www.firsttimersonly.com/ may help a bit more. 

FOSS Responders, though, is largely holding off on more code work, for now, until we need to ramp up again. More messaging on this is coming soon. Mentoring at the moment isn't a high priority for me on this project, though, as it's simply not going to be used much.

**Comment by Ruth-ikegah** [comment]
> Thanks, @Ruth-ikegah! https://www.firsttimersonly.com/ may help a bit more.
> 
> FOSS Responders, though, is largely holding off on more code work, for now, until we need to ramp up again. More messaging on this is coming soon. Mentoring at the moment isn't a high priority for me on this project, though, as it's simply not going to be used much.

Thanks

**Comment by RichardLitt** [comment]
Stale. Feel free to reopen if you feel it is necessary.
