### ISSUE TITLE
Create buttons for "I want to help"

### ISSUE THREAD

**Issue by rachellawson** [foss-responders/fossresponders.com#8]
We probably need to look at buttons, equivalent to the "I want help" buttons, that link through to the OpenCollective options for funding the project. Should be able to drag these straight out of OC.

**Comment by rachellawson** [comment]
I think we are ending up with a slightly "vague" content structure on front page, slowly. Will need a review of that.

Maybe something 

- Can we help?
- Can you help us?
- Who is helping already? (this being in subcategories of time, talent, and treasure)
- Where else can I find help?

**Comment by Erioldoesdesign** [comment]
Hmm I've done app/services structures very much like this before and we went with this:

<img width="281" alt="Screen Shot 2019-02-06 at 01 21 52" src="https://user-images.githubusercontent.com/11681324/76991324-4c2c8c00-6941-11ea-94cc-811f42a9b516.png">
<img width="281" alt="Screen Shot 2019-02-06 at 01 22 55" src="https://user-images.githubusercontent.com/11681324/76991327-4e8ee600-6941-11ea-9645-766ba6e908d6.png">


So we separated 'I want help' and 'I can offer help' into separate 'flows'
But we built in Ionic web app so we had certain available structures. But we user-tested this menu/button structure.

**Comment by Erioldoesdesign** [comment]
How can I make some design progress on this? I'm happy to do some mock-ups/designs of what I think might be best UX wise but want to be compassionate to who is coding so I'm not ignoring limitations of the BE/FEsystem!

**Comment by rachellawson** [comment]
I think there is a need to look at this, yes. Also the wide UX of the front page - needs to create a sense of “this is the real deal” to both those needing help AND those who can give

**Comment by Erioldoesdesign** [comment]
@RichardLitt https://fossresponders.com/ is a github pages site right? Any other limitations that I should know about if I'm gonna do design stuff?

**Comment by RichardLitt** [comment]
@Erioldoesdesign Yes, it is. Not sure there are any other limitations. Should've used Bootstrap, but didn't might redo it in Bootstrap at some point, for better ARIA stuff.

**Comment by RichardLitt** [comment]
> How can I make some design progress on this? I'm happy to do some mock-ups/designs of what I think might be best UX wise but want to be compassionate to who is coding so I'm not ignoring limitations of the BE/FEsystem!

Send me any designs you got! This is fairly basic; I want to go with the best. If you have better ideas, let me implement them. :)

**Comment by Erioldoesdesign** [comment]
Okay so this is definitely not 'just' the two sections of the web page but more a look at how Foss responders could layout it's information alongside an 'identity'

Please find the adobe xd prototype link here: https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/

If you click the little </> icon on the right you'll get 'developer info' like hex codes etc.

All blue links and buttons would link externally - This then remains a 1 pager site with sectioned content :)
Many of the links would go to sections in our Discourse.

Content of sections still needs review by folks alongside the messaging document: https://docs.google.com/document/d/1xh7F_IsYkJPz6WXxe5Y__k7QNZFAfIvE-chnOAvghuM/edit?ts=5e78c0fa#heading=h.q3z98i6ieiix

I know @awright said she could look at messaging/content here.

**Comment by Erioldoesdesign** [comment]
Also a folder with various useful files?

https://drive.google.com/drive/folders/185aEK0vOxGMB_773kGdQvPa0CU6dmPIj?usp=sharing

**Comment by RichardLitt** [comment]
This is great, @Erioldoesdesign! I love these designs. 

The messaging does need to be tightened. Along with @awright, I've talked to Megan about aligning the current content to our messaging doc. I'll take a stab at the content for this. If I understand, you'll hold off on redesigning specifically, and me in implementing that design, until this is done, correct?

**Comment by Erioldoesdesign** [comment]
1000% happy to pass on the content structure/IA to yourself, Megan and Alyssa. 

Hopefully, this design is flexible enough that It could have more/different content/copy injected or new sections below the needs/offers sections but let me know if anything is particularly tricky to work in and needs a design eye. So please go for it unless you need me

**Comment by Erioldoesdesign** [comment]
Website homepage updated to reflect the info in this doc: https://docs.google.com/document/d/1KRqxX_vRZnnc_vuE5qMcvpcbl_DOPgEaiKNKznpvuA8/edit?ts=5e8619b3#

Here's the Adobe XD prototype link: https://xd.adobe.com/view/8e9576cb-18da-4d9f-58b8-7d00d753377f-f8a4/

**Comment by Erioldoesdesign** [comment]
I *think* we can close this as this ticket led to the 'design' of the homepage which has now been split into dev tickets?

**Comment by RichardLitt** [comment]
I agree with that assumption. Thanks, @Erioldoesdesign.
