### ISSUE TITLE
Twitter card doesn't work.

### ISSUE THREAD

**Issue by RichardLitt** [foss-responders/fossresponders.com#80]
Please fix it, me. :)

**Comment by awelllle** [comment]
The one the footer? I clicked and it took me to foss's Twitter

**Comment by RichardLitt** [comment]
<img width="604" alt="Screen Shot 2020-05-01 at 20 37 42" src="https://user-images.githubusercontent.com/910753/80850776-9fa22300-8beb-11ea-9f91-e6b8595b8a5e.png">

Note the lack of the image. This needs to be set correctly in the header.

**Comment by SaptakS** [comment]
Weirdly enough, the twitter card validator actually shows the preview correctly: https://cards-dev.twitter.com/validator I am just wondering if it is because we are showing favicon image (which is super small)

**Comment by RichardLitt** [comment]
Good catch. This should be fixed now. :)
