### ISSUE TITLE
Address target=_blank vulnerability

### ISSUE THREAD

**Issue by SaptakS** [foss-responders/fossresponders.com#84]
We are using `target=_blank` in many places throughout the website for opening links pointing to different websites. `target=_blank` has a [vulnerability](https://mathiasbynens.github.io/rel-noopener/). 

We need to add `rel="noopener noreferrer"` for all `target=_blank` link.

I will send a PR for the same.

**Comment by RichardLitt** [comment]
Good catch. I didn't know about this. Thanks!
