### ISSUE TITLE
Logos overlap when div id "logos" is 720px wide 

### ISSUE THREAD

**Issue by DuaneOBrien** [foss-responders/fossresponders.com#99]
When viewing the Logos section of fossresponders.com and resizing the window, the logos appear overlapped when div id "logos" is 720px wide.

Attaching screenshots.

540px wide
![540-wide](https://user-images.githubusercontent.com/4315550/81901169-f0623600-9572-11ea-8933-5550c6708b78.png)

720px wide
![720-wide](https://user-images.githubusercontent.com/4315550/81901192-f7894400-9572-11ea-86c3-098f813f0b55.png)

960px wide
![960-wide](https://user-images.githubusercontent.com/4315550/81901214-ffe17f00-9572-11ea-8f4b-b4aaada8caa1.png)

1140px wide
![1140-wide](https://user-images.githubusercontent.com/4315550/81901239-066ff680-9573-11ea-9204-6d77fb0461e7.png)

macOS Catalina 10.15.3
Chrome 81.0.4044.138

**Comment by SaptakS** [comment]
@DuaneOBrien Thanks for opening this. I will look into it in some time.

**Comment by RichardLitt** [comment]
Thank you!

**Comment by RichardLitt** [comment]
Merged and fixed.
